import Head from 'next/head'
import { Button, ThemeToggle } from '@/components'

function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <Button>你好</Button>
        <ThemeToggle />
      </main>
    </>
  )
}

export default Home
